name: 📋 PR

on:
  pull_request: {}
  workflow_dispatch: {}

permissions: {}

jobs:
  build:
    name: 📦🔍 Build Check
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: 🛠️ Setup Node.js Environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: 🛠️ Setup Project
        run: npm ci

      - name: 🛠️ Build
        run: npm run compile
